# Generated by Django 4.2.6 on 2023-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layanan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="layananpemerintahan",
            name="keterangan",
            field=models.CharField(default="-", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layananpemerintahan",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                default="-",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layananumum",
            name="keterangan",
            field=models.CharField(default="-", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layananumum",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                default="-",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="layananpemerintahan",
            name="keperluan",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="layananumum",
            name="keperluan",
            field=models.CharField(max_length=32),
        ),
    ]
