# Generated by Django 4.2.6 on 2023-10-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datamaster", "0001_initial"),
        ("layanan", "0002_layananpemerintahan_keterangan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layananpemerintahan",
            name="desa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datamaster.desa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layananumum",
            name="desa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="datamaster.desa",
            ),
            preserve_default=False,
        ),
    ]
