# Generated by Django 4.2.6 on 2023-10-16 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datamaster", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layanan", "0003_layananpemerintahan_desa_layananumum_desa"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayananHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("obj_id", models.BigIntegerField()),
                (
                    "obj_type",
                    models.CharField(
                        choices=[
                            ("pemerintahan", "Layanan Pemerintahan"),
                            ("umum", "Layanan Umum"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Diterima"),
                            ("accepted", "Disetujui oleh Kepala Bagian"),
                            ("rejected", "Ditolak oleh Kepala Bagian"),
                            ("approved", "Disetujui oleh Kepala Desa"),
                            ("success", "Dicetak"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layanan_history_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamaster.desa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layanan_history_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "layanan_history",
            },
        ),
        migrations.AlterField(
            model_name="layananpemerintahan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="layananpemerintahan",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="layananumum",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="layananumum",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LayananHistoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Diterima"),
                            ("accepted", "Disetujui oleh Kepala Bagian"),
                            ("rejected", "Ditolak oleh Kepala Bagian"),
                            ("approved", "Disetujui oleh Kepala Desa"),
                            ("success", "Dicetak"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_detail_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="layanan.layananhistory",
                    ),
                ),
            ],
            options={
                "db_table": "layanan_history_detail",
            },
        ),
    ]
