# Generated by Django 4.2.6 on 2023-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layanan", "0004_create_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layananhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("correction", "Diperbaiki oleh Penduduk"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="layananhistorydetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("correction", "Diperbaiki oleh Penduduk"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="layananpemerintahan",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("correction", "Diperbaiki oleh Penduduk"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="layananumum",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Diterima"),
                    ("accepted", "Disetujui oleh Kepala Bagian"),
                    ("rejected", "Ditolak oleh Kepala Bagian"),
                    ("correction", "Diperbaiki oleh Penduduk"),
                    ("approved", "Disetujui oleh Kepala Desa"),
                    ("success", "Dicetak"),
                ],
                max_length=16,
            ),
        ),
    ]
