# Generated by Django 4.2.3 on 2023-07-14 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                ("identifier", models.IntegerField(primary_key=True, serialize=False)),
                ("task_id", models.CharField(max_length=32, unique=True)),
                ("status", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "background_task",
            },
        ),
        migrations.CreateModel(
            name="QueuedNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("receivers", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
